### ISSUE TITLE
Weights files missing. 

### ISSUE THREAD

**Issue by WAKEYOU** [TwentyBN/sense#191]
Hello，Weights files missing. To download, please go to https://20bn.com/licensing/sdk/evaluation andfollow the instructions.However, this website cannot be logged in. Could you please provide the pre-training weight file ？ Thank you very much!

**Comment by lindychan** [comment]
I found the same problem.

**Comment by mateuszdargacz** [comment]
@WAKEYOU  @corneliusboehm  @ingooooooo  @lindychan  can you share the Weights files?

**Comment by WAKEYOU** [comment]
> @WAKEYOU @corneliusboehm @ingooooooo @lindychan can you share the Weights files?
Sorry, I haven't got the weight file yet

**Comment by mateuszdargacz** [comment]
@WAKEYOU I have found the weight files for the `fitness_activity_recognition`, `action_recognition `  etc. while browsing repo's commits, and the backbone weights as well (which wasn't that easy 😄 ). Here are the  [weights](https://drive.google.com/file/d/1OahVVN2l7HT96nwWFT_CcFtDcf-4MhjJ/view?usp=sharing) I used.

**Comment by aureosun** [comment]
@mateuszdargacz did you get the demo running? I tried to run the gesture control,but with the outcome
python examples/run_gesture_control.py
Could not find at least one of the following files:
{
    "backbone": "backbone/strided_inflated_efficientnet.ckpt",
    "gesture_control": "gesture_control/sien_last_9_layers.ckpt"
}
Could not find at least one of the following files:
{
    "backbone": "backbone/strided_inflated_efficientnet_lite.ckpt",
    "gesture_control": "gesture_control/sien_lite_last_9_layers.ckpt"
}
ERROR - Weights files missing. To download, please go to https://20bn.com/licensing/sdk/evaluation andfollow the instructions.
Traceback (most recent call last):
  File "D:\sense\examples\run_gesture_control.py", line 135, in <module>
    run_gesture_control(
  File "D:\sense\examples\run_gesture_control.py", line 69, in run_gesture_control
    selected_config, weights = get_relevant_weights(
  File "D:\sense\sense\loading.py", line 150, in get_relevant_weights
    raise Exception(msg)
Exception: ERROR - Weights files missing. To download, please go to https://20bn.com/licensing/sdk/evaluation andfollow the instructions.

any suggestions ? thanks

**Comment by mateuszdargacz** [comment]
@aureosun  as I mentioned in my last comment I used the files from this [url](https://drive.google.com/file/d/1OahVVN2l7HT96nwWFT_CcFtDcf-4MhjJ/view?usp=sharing). it contains the files which  you pointed to be missing.

**Comment by aureosun** [comment]
@mateuszdargacz  I downloaded the weights, but it still not work with the outcome as mentioned above, could you please give me some suggestions?
